#!/bin/bash

# Script to add location permission keys to the Info.plist that's generated by Xcode
# Run this script to modify the project build settings

PROJECT_FILE="DailyMile.xcodeproj/project.pbxproj"

# Check if project file exists
if [ ! -f "$PROJECT_FILE" ]; then
    echo "Error: Project file not found: $PROJECT_FILE"
    exit 1
fi

# First, make a backup of the project file
cp "$PROJECT_FILE" "${PROJECT_FILE}.bak"
echo "Created backup at ${PROJECT_FILE}.bak"

# Add location permission keys to both Debug and Release configurations
sed -i '' '/GENERATE_INFOPLIST_FILE = YES;/a\
				INFOPLIST_KEY_NSLocationWhenInUseUsageDescription = "The Daily Mile needs your location to track your running routes and calculate distance.";\
				INFOPLIST_KEY_NSLocationAlwaysAndWhenInUseUsageDescription = "The Daily Mile needs your location to track your running routes and calculate distance, even when the app is in background.";' "$PROJECT_FILE"

echo "Added location permission keys to project build settings"
echo "You can now build the project and the permissions will be added to the generated Info.plist" 